"""The §3 state machine as an Alloy 6 model, generated from fsm.py (docs/alloy/README.md).

The table in fsm.py is the one source: this module renders its 41 rows and sub-project 15's
three extension rows as Alloy facts, and docs/alloy/fsm_checks.als - written by hand - states the
properties Alloy checks over every trace of that model. tests/test_alloy_model.py fails if the
committed docs/alloy/fsm_model.als drifts from what this module renders, so a change to the table
cannot leave the Alloy model behind.

What is modelled: the State, the escalation kind the case carries, and which row fired last.
What is not: the guards' values. A guard is a condition the State Manager evaluates at run time;
here every row's guards are abstracted to "may hold", so a property Alloy proves holds for any
guard outcome - the strongest form. A property that needs a guard is stated in fsm_checks.als
with that guard as an explicit, named assumption.

    docker compose run --rm backend python -m hospital_agent.policy.alloy_model > docs/alloy/fsm_model.als
"""
from __future__ import annotations

import sys

from ..fsm import EXTENSION_TRANSITIONS, TRANSITIONS, Transition
from ..naming import EscalationKind, Event, State

TERMINAL = (State.COMPLETED, State.FAILED)


def _row_name(index: int) -> str:
    return f"R{index:02d}"


def _set(names: list[str]) -> str:
    return " + ".join(names) if names else "none"


def _row(index: int, row: Transition) -> str:
    kinds = sorted(k.value for k in row.escalation.kinds) if row.escalation else []
    requires = sorted(k.value for k in row.requires_escalation) if row.requires_escalation else []
    source = "no src" if row.source is None else f"src = {row.source.value}"
    guards = ", ".join(row.guards) if row.guards else "-"
    return (f"-- {_row_name(index)}: {row.source.value if row.source else 'Initial'} --{row.event.value}--> "
            f"{row.target.value}   [guards: {guards}]\n"
            f"one sig {_row_name(index)} extends Row {{}} {{\n"
            f"  {source}\n  ev = {row.event.value}\n  dst = {row.target.value}\n"
            f"  kinds = {_set(kinds)}\n  requires = {_set(requires)}\n"
            f"  extension = {'True' if row in EXTENSION_TRANSITIONS else 'False'}\n}}\n")


def render() -> str:
    rows = TRANSITIONS + EXTENSION_TRANSITIONS
    events = sorted({row.event.value for row in rows})
    states = [s.value for s in State]
    kinds = [k.value for k in EscalationKind]
    parts = [
        "-- GENERATED by `python -m hospital_agent.policy.alloy_model` from backend/hospital_agent/fsm.py.",
        "-- Do not edit: change fsm.py (and the spec first), then regenerate. tests/test_alloy_model.py",
        f"-- fails if this file drifts. {len(TRANSITIONS)} §3 rows + {len(EXTENSION_TRANSITIONS)} extension rows.",
        "module fsm_model",
        "",
        "abstract sig Bool {}",
        "one sig True, False extends Bool {}",
        "",
        "abstract sig State {}",
        f"one sig {', '.join(states)} extends State {{}}",
        f"fun Terminal: set State {{ {' + '.join(s.value for s in TERMINAL)} }}",
        "",
        "abstract sig Event {}",
        f"one sig {', '.join(events)} extends Event {{}}",
        "",
        "abstract sig Kind {}",
        f"one sig {', '.join(kinds)} extends Kind {{}}",
        "",
        "-- One row of the transition table. `kinds`: the escalation kinds the row may record;",
        "-- `requires`: the kind a HUMAN_APPROVED row needs the case to carry.",
        "abstract sig Row {",
        "  src: lone State,  -- none = Initial",
        "  ev: one Event,",
        "  dst: one State,",
        "  kinds: set Kind,",
        "  requires: set Kind,",
        "  extension: one Bool",
        "}",
        "",
    ]
    parts += [_row(i, row) for i, row in enumerate(rows, 1)]
    parts += [
        "-- The one case a trace follows (Alloy 6: `var` fields change from step to step).",
        "one sig Case {",
        "  var state: lone State,    -- none = Initial, before REQUEST_SUBMITTED",
        "  var escalation: lone Kind,",
        "  var last: lone Row,       -- the row that brought the case here",
        "  var moved: one Bool       -- True on a step where a row fired, False on a stutter",
        "}",
        "",
        "pred init { no Case.state and no Case.escalation and no Case.last and Case.moved = False }",
        "",
        "-- Row r fires: the case is in r's source (Initial when r has none), carries the kind r",
        "-- requires (if any), and moves to r's target. An escalation row records one of its kinds;",
        "-- the reply cycle (AwaitingHumanReview <-> AwaitingPatientReply) keeps the kind; any other",
        "-- row clears it (fsm.py: CLEAR_ESCALATION on resume; a terminal row ends the case).",
        "pred fire[r: Row] {",
        "  Case.state = r.src",
        "  some r.requires implies (one Case.escalation and Case.escalation in r.requires)",
        "  Case.state' = r.dst",
        "  Case.last' = r",
        "  Case.moved' = True",
        "  some r.kinds implies Case.escalation' in r.kinds and one Case.escalation'",
        "  (no r.kinds and r.dst in AwaitingHumanReview + AwaitingPatientReply) implies Case.escalation' = Case.escalation",
        "  (no r.kinds and r.dst not in AwaitingHumanReview + AwaitingPatientReply) implies no Case.escalation'",
        "}",
        "",
        "pred stutter {",
        "  Case.state' = Case.state and Case.escalation' = Case.escalation and Case.last' = Case.last",
        "  Case.moved' = False",
        "}",
        "",
        "fact traces { init and always (stutter or some r: Row | fire[r]) }",
        "",
    ]
    return "\n".join(parts)


if __name__ == "__main__":
    sys.stdout.write(render())
