-- GENERATED by `python -m hospital_agent.policy.alloy_model` from backend/hospital_agent/fsm.py.
-- Do not edit: change fsm.py (and the spec first), then regenerate. tests/test_alloy_model.py
-- fails if this file drifts. 41 §3 rows + 3 extension rows.
module fsm_model

abstract sig Bool {}
one sig True, False extends Bool {}

abstract sig State {}
one sig Received, Classifying, Classified, Planning, RetrievingData, Delivering, AssessingReadiness, AwaitingPatientInput, AwaitingHumanReview, Ready, Completed, Failed, AwaitingPatientReply extends State {}
fun Terminal: set State { Completed + Failed }

abstract sig Event {}
one sig ACTION_PROPOSED, CASE_RESOLVED, DATA_RETRIEVED, DELIVERY_PLANNED, DOCUMENT_UPLOADED, HUMAN_APPROVED, HUMAN_REJECTED, HUMAN_RESOLVED_CASE, HUMAN_REVIEW_REQUIRED, INTENT_CLASSIFIED, MEDICAL_QUESTION_DETECTED, MISSING_INFORMATION_DETECTED, PATIENT_REPLY_REQUESTED, PATIENT_REPLY_SUBMITTED, PATIENT_VERIFICATION_FAILED, PLAN_CREATED, POLICY_ALLOWED, POLICY_DENIED, POLICY_HUMAN_REVIEW_REQUIRED, READINESS_PASSED, REQUEST_SUBMITTED, REQUEST_VALIDATED, RETRY_EXHAUSTED, STEP_ADVANCED, TIMEOUT_EXPIRED, TOOL_TRANSIENT_FAILURE extends Event {}

abstract sig Kind {}
one sig PatientVerificationFailed, MedicalQuestion, SafetyEscalation, ClassificationFailed, TemporalViolation, PlanningFailed, PolicyDenied, PolicyReview, RetryExhausted, NonIdempotentFailure, ExecutionUnknown, Z3Counterexample, PatientSlaExpired, DeliveryStepMissing extends Kind {}

-- One row of the transition table. `kinds`: the escalation kinds the row may record;
-- `requires`: the kind a HUMAN_APPROVED row needs the case to carry.
abstract sig Row {
  src: lone State,  -- none = Initial
  ev: one Event,
  dst: one State,
  kinds: set Kind,
  requires: set Kind,
  extension: one Bool
}

-- R01: Initial --REQUEST_SUBMITTED--> Received   [guards: PatientIdentified]
one sig R01 extends Row {} {
  no src
  ev = REQUEST_SUBMITTED
  dst = Received
  kinds = none
  requires = none
  extension = False
}

-- R02: Received --REQUEST_VALIDATED--> Classifying   [guards: RequestValid, IdentityVerified]
one sig R02 extends Row {} {
  src = Received
  ev = REQUEST_VALIDATED
  dst = Classifying
  kinds = none
  requires = none
  extension = False
}

-- R03: Received --PATIENT_VERIFICATION_FAILED--> AwaitingHumanReview   [guards: -]
one sig R03 extends Row {} {
  src = Received
  ev = PATIENT_VERIFICATION_FAILED
  dst = AwaitingHumanReview
  kinds = PatientVerificationFailed
  requires = none
  extension = False
}

-- R04: Classifying --INTENT_CLASSIFIED--> Classified   [guards: valid_classification, !ReadinessInProgress]
one sig R04 extends Row {} {
  src = Classifying
  ev = INTENT_CLASSIFIED
  dst = Classified
  kinds = none
  requires = none
  extension = False
}

-- R05: Classifying --INTENT_CLASSIFIED--> AssessingReadiness   [guards: valid_classification, ReadinessInProgress]
one sig R05 extends Row {} {
  src = Classifying
  ev = INTENT_CLASSIFIED
  dst = AssessingReadiness
  kinds = none
  requires = none
  extension = False
}

-- R06: Classifying --MEDICAL_QUESTION_DETECTED--> AwaitingHumanReview   [guards: -]
one sig R06 extends Row {} {
  src = Classifying
  ev = MEDICAL_QUESTION_DETECTED
  dst = AwaitingHumanReview
  kinds = MedicalQuestion
  requires = none
  extension = False
}

-- R07: Classifying --HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: SystemEscalationRequired]
one sig R07 extends Row {} {
  src = Classifying
  ev = HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = ClassificationFailed + SafetyEscalation + TemporalViolation
  requires = none
  extension = False
}

-- R08: Classified --PLAN_CREATED--> Planning   [guards: PlanComplete]
one sig R08 extends Row {} {
  src = Classified
  ev = PLAN_CREATED
  dst = Planning
  kinds = none
  requires = none
  extension = False
}

-- R09: Classified --HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: SystemEscalationRequired]
one sig R09 extends Row {} {
  src = Classified
  ev = HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = PlanningFailed + TemporalViolation
  requires = none
  extension = False
}

-- R10: Planning --ACTION_PROPOSED--> Planning   [guards: InPlan, PlanIntact]
one sig R10 extends Row {} {
  src = Planning
  ev = ACTION_PROPOSED
  dst = Planning
  kinds = none
  requires = none
  extension = False
}

-- R11: Planning --STEP_ADVANCED--> Planning   [guards: PlanIntact, CanAdvance]
one sig R11 extends Row {} {
  src = Planning
  ev = STEP_ADVANCED
  dst = Planning
  kinds = none
  requires = none
  extension = False
}

-- R12: Planning --POLICY_ALLOWED--> RetrievingData   [guards: ExecutorReverified, retrieval_action]
one sig R12 extends Row {} {
  src = Planning
  ev = POLICY_ALLOWED
  dst = RetrievingData
  kinds = none
  requires = none
  extension = False
}

-- R13: Planning --POLICY_ALLOWED--> Delivering   [guards: ExecutorReverified, delivery_action]
one sig R13 extends Row {} {
  src = Planning
  ev = POLICY_ALLOWED
  dst = Delivering
  kinds = none
  requires = none
  extension = False
}

-- R14: Planning --POLICY_DENIED--> AwaitingHumanReview   [guards: -]
one sig R14 extends Row {} {
  src = Planning
  ev = POLICY_DENIED
  dst = AwaitingHumanReview
  kinds = PolicyDenied
  requires = none
  extension = False
}

-- R15: Planning --POLICY_HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: -]
one sig R15 extends Row {} {
  src = Planning
  ev = POLICY_HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = PolicyReview
  requires = none
  extension = False
}

-- R16: Planning --HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: SystemEscalationRequired]
one sig R16 extends Row {} {
  src = Planning
  ev = HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = PlanningFailed + TemporalViolation
  requires = none
  extension = False
}

-- R17: RetrievingData --DATA_RETRIEVED--> Planning   [guards: valid_tool_result, RetrievalStepsRemain]
one sig R17 extends Row {} {
  src = RetrievingData
  ev = DATA_RETRIEVED
  dst = Planning
  kinds = none
  requires = none
  extension = False
}

-- R18: RetrievingData --DATA_RETRIEVED--> AssessingReadiness   [guards: valid_tool_result, PreReadinessPhaseComplete]
one sig R18 extends Row {} {
  src = RetrievingData
  ev = DATA_RETRIEVED
  dst = AssessingReadiness
  kinds = none
  requires = none
  extension = False
}

-- R19: RetrievingData --TOOL_TRANSIENT_FAILURE--> Planning   [guards: AttemptsAvailable, IsIdempotent]
one sig R19 extends Row {} {
  src = RetrievingData
  ev = TOOL_TRANSIENT_FAILURE
  dst = Planning
  kinds = none
  requires = none
  extension = False
}

-- R20: RetrievingData --RETRY_EXHAUSTED--> AwaitingHumanReview   [guards: -]
one sig R20 extends Row {} {
  src = RetrievingData
  ev = RETRY_EXHAUSTED
  dst = AwaitingHumanReview
  kinds = RetryExhausted
  requires = none
  extension = False
}

-- R21: RetrievingData --HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: SystemEscalationRequired]
one sig R21 extends Row {} {
  src = RetrievingData
  ev = HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = ExecutionUnknown + NonIdempotentFailure + TemporalViolation
  requires = none
  extension = False
}

-- R22: Delivering --CASE_RESOLVED--> Completed   [guards: DeliveryConfirmed, ReadinessComplete]
one sig R22 extends Row {} {
  src = Delivering
  ev = CASE_RESOLVED
  dst = Completed
  kinds = none
  requires = none
  extension = False
}

-- R23: Delivering --TOOL_TRANSIENT_FAILURE--> Planning   [guards: AttemptsAvailable, IsIdempotent]
one sig R23 extends Row {} {
  src = Delivering
  ev = TOOL_TRANSIENT_FAILURE
  dst = Planning
  kinds = none
  requires = none
  extension = False
}

-- R24: Delivering --RETRY_EXHAUSTED--> AwaitingHumanReview   [guards: -]
one sig R24 extends Row {} {
  src = Delivering
  ev = RETRY_EXHAUSTED
  dst = AwaitingHumanReview
  kinds = RetryExhausted
  requires = none
  extension = False
}

-- R25: Delivering --HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: SystemEscalationRequired]
one sig R25 extends Row {} {
  src = Delivering
  ev = HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = ExecutionUnknown + NonIdempotentFailure + TemporalViolation
  requires = none
  extension = False
}

-- R26: AssessingReadiness --READINESS_PASSED--> Ready   [guards: ReadinessComplete]
one sig R26 extends Row {} {
  src = AssessingReadiness
  ev = READINESS_PASSED
  dst = Ready
  kinds = none
  requires = none
  extension = False
}

-- R27: AssessingReadiness --MISSING_INFORMATION_DETECTED--> AwaitingPatientInput   [guards: deadline_registered, !ReadinessComplete, AskPatientSafe]
one sig R27 extends Row {} {
  src = AssessingReadiness
  ev = MISSING_INFORMATION_DETECTED
  dst = AwaitingPatientInput
  kinds = none
  requires = none
  extension = False
}

-- R28: AssessingReadiness --HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: SystemEscalationRequired]
one sig R28 extends Row {} {
  src = AssessingReadiness
  ev = HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = TemporalViolation + Z3Counterexample
  requires = none
  extension = False
}

-- R29: AwaitingPatientInput --DOCUMENT_UPLOADED--> Classifying   [guards: DocumentValid]
one sig R29 extends Row {} {
  src = AwaitingPatientInput
  ev = DOCUMENT_UPLOADED
  dst = Classifying
  kinds = none
  requires = none
  extension = False
}

-- R30: AwaitingPatientInput --DOCUMENT_UPLOADED--> AwaitingPatientInput   [guards: !DocumentValid]
one sig R30 extends Row {} {
  src = AwaitingPatientInput
  ev = DOCUMENT_UPLOADED
  dst = AwaitingPatientInput
  kinds = none
  requires = none
  extension = False
}

-- R31: AwaitingPatientInput --TIMEOUT_EXPIRED--> AwaitingHumanReview   [guards: PatientSlaExpired]
one sig R31 extends Row {} {
  src = AwaitingPatientInput
  ev = TIMEOUT_EXPIRED
  dst = AwaitingHumanReview
  kinds = PatientSlaExpired
  requires = none
  extension = False
}

-- R32: Ready --DELIVERY_PLANNED--> Planning   [guards: PlanIntact, CanAdvance, DeliveryStepPending]
one sig R32 extends Row {} {
  src = Ready
  ev = DELIVERY_PLANNED
  dst = Planning
  kinds = none
  requires = none
  extension = False
}

-- R33: Ready --HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: SystemEscalationRequired]
one sig R33 extends Row {} {
  src = Ready
  ev = HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = DeliveryStepMissing + TemporalViolation
  requires = none
  extension = False
}

-- R34: Received --HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: SystemEscalationRequired]
one sig R34 extends Row {} {
  src = Received
  ev = HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = TemporalViolation
  requires = none
  extension = False
}

-- R35: AwaitingPatientInput --HUMAN_REVIEW_REQUIRED--> AwaitingHumanReview   [guards: SystemEscalationRequired]
one sig R35 extends Row {} {
  src = AwaitingPatientInput
  ev = HUMAN_REVIEW_REQUIRED
  dst = AwaitingHumanReview
  kinds = TemporalViolation
  requires = none
  extension = False
}

-- R36: AwaitingHumanReview --HUMAN_APPROVED--> Received   [guards: WorkflowDecisionValid]
one sig R36 extends Row {} {
  src = AwaitingHumanReview
  ev = HUMAN_APPROVED
  dst = Received
  kinds = none
  requires = PatientVerificationFailed
  extension = False
}

-- R37: AwaitingHumanReview --HUMAN_APPROVED--> Planning   [guards: WorkflowDecisionValid]
one sig R37 extends Row {} {
  src = AwaitingHumanReview
  ev = HUMAN_APPROVED
  dst = Planning
  kinds = none
  requires = RetryExhausted
  extension = False
}

-- R38: AwaitingHumanReview --HUMAN_APPROVED--> Planning   [guards: WorkflowDecisionValid]
one sig R38 extends Row {} {
  src = AwaitingHumanReview
  ev = HUMAN_APPROVED
  dst = Planning
  kinds = none
  requires = PolicyReview
  extension = False
}

-- R39: AwaitingHumanReview --HUMAN_APPROVED--> AwaitingPatientInput   [guards: WorkflowDecisionValid]
one sig R39 extends Row {} {
  src = AwaitingHumanReview
  ev = HUMAN_APPROVED
  dst = AwaitingPatientInput
  kinds = none
  requires = PatientSlaExpired + Z3Counterexample
  extension = False
}

-- R40: AwaitingHumanReview --HUMAN_RESOLVED_CASE--> Completed   [guards: WorkflowDecisionValid, closure_reason]
one sig R40 extends Row {} {
  src = AwaitingHumanReview
  ev = HUMAN_RESOLVED_CASE
  dst = Completed
  kinds = none
  requires = none
  extension = False
}

-- R41: AwaitingHumanReview --HUMAN_REJECTED--> Failed   [guards: WorkflowDecisionValid]
one sig R41 extends Row {} {
  src = AwaitingHumanReview
  ev = HUMAN_REJECTED
  dst = Failed
  kinds = none
  requires = none
  extension = False
}

-- R42: AwaitingHumanReview --PATIENT_REPLY_REQUESTED--> AwaitingPatientReply   [guards: WorkflowDecisionValid, reply_request_valid]
one sig R42 extends Row {} {
  src = AwaitingHumanReview
  ev = PATIENT_REPLY_REQUESTED
  dst = AwaitingPatientReply
  kinds = none
  requires = none
  extension = True
}

-- R43: AwaitingPatientReply --PATIENT_REPLY_SUBMITTED--> AwaitingHumanReview   [guards: patient_reply_valid]
one sig R43 extends Row {} {
  src = AwaitingPatientReply
  ev = PATIENT_REPLY_SUBMITTED
  dst = AwaitingHumanReview
  kinds = none
  requires = none
  extension = True
}

-- R44: AwaitingPatientReply --TIMEOUT_EXPIRED--> AwaitingHumanReview   [guards: PatientSlaExpired]
one sig R44 extends Row {} {
  src = AwaitingPatientReply
  ev = TIMEOUT_EXPIRED
  dst = AwaitingHumanReview
  kinds = none
  requires = none
  extension = True
}

-- The one case a trace follows (Alloy 6: `var` fields change from step to step).
one sig Case {
  var state: lone State,    -- none = Initial, before REQUEST_SUBMITTED
  var escalation: lone Kind,
  var last: lone Row,       -- the row that brought the case here
  var moved: one Bool       -- True on a step where a row fired, False on a stutter
}

pred init { no Case.state and no Case.escalation and no Case.last and Case.moved = False }

-- Row r fires: the case is in r's source (Initial when r has none), carries the kind r
-- requires (if any), and moves to r's target. An escalation row records one of its kinds;
-- the reply cycle (AwaitingHumanReview <-> AwaitingPatientReply) keeps the kind; any other
-- row clears it (fsm.py: CLEAR_ESCALATION on resume; a terminal row ends the case).
pred fire[r: Row] {
  Case.state = r.src
  some r.requires implies (one Case.escalation and Case.escalation in r.requires)
  Case.state' = r.dst
  Case.last' = r
  Case.moved' = True
  some r.kinds implies Case.escalation' in r.kinds and one Case.escalation'
  (no r.kinds and r.dst in AwaitingHumanReview + AwaitingPatientReply) implies Case.escalation' = Case.escalation
  (no r.kinds and r.dst not in AwaitingHumanReview + AwaitingPatientReply) implies no Case.escalation'
}

pred stutter {
  Case.state' = Case.state and Case.escalation' = Case.escalation and Case.last' = Case.last
  Case.moved' = False
}

fact traces { init and always (stutter or some r: Row | fire[r]) }
